name: Automated tests for Elevator Simulator
on:
  pull_request:
    branches:
      - development
      - main
jobs:
  build_and_test_simulator:
    name: Build Simulator Executable and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Restore packages and build
        run: |
          dotnet restore
          dotnet build --configuration Release
          cd tests/ElevatorSimulator.UnitTests
          dotnet test ElevatorSimulator.UnitTests.csproj
      