name: Automated tests for Elevator Simulator
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build_simulator:
    name: Build Simulator
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore packages and build
        run: |
          dotnet restore
          dotnet build --configuration Release
          
      
      - name: Create release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            artifacts: "*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
        
        
  
    